version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.5.0
    shell: zsh

    steps:
      - checkout
      - sonarcloud/scan:
          os: macosx
          cache_version:

  grab-screenshots:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Snapshots
          command: cd src/xcode && bundle exec fastlane snapshot
      - store_artifacts:
          path: src/xcode/screenshots

orbs:
  sonarcloud: tkowark/sonarcloud2@0.1.0
workflows:
    default:
      jobs:
        - build-and-test
