version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.5.0
    shell: zsh

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: brew install swiftlint && brew install wget && cd src/xcode && bundle install
      - run:
          name: Build
          command: cd src/xcode && bundle exec fastlane build
      - run:
          name: Tests
          command: cd src/xcode && bundle exec fastlane test
      - sonarcloud/install-cli:
          os: macosx
          no-cache: true
      - sonarcloud/scan-on-branch-commit:
          cache-version: v42
          github-project-slug: corona-warn-app/cwa-app-ios
          project-key: corona-warn-app_cwa-app-ios
      - store_test_results:
          path: src/xcode/fastlane/test_output
      - store_artifacts:
          path: src/xcode/fastlane/test_output

  grab-screenshots:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Snapshots
          command: cd src/xcode && bundle exec fastlane snapshot
      - store_artifacts:
          path: src/xcode/screenshots

orbs:
  sonarcloud: socialtables/sonarcloud@1.1.1
workflows:
    default:
      jobs:
        - build-and-test
